/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codes.pedromanoel.learning.cleancode;

import org.junit.Test;
import static org.junit.Assert.*;

public class PrintPrimesTest {
    @Test public void main() {
        PrintPrimes.main(new String[]{});
    }
}
