/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codes.pedromanoel.learning.cleancode;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
